# Generated by Django 4.1.3 on 2024-07-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platter_App', '0002_alter_branch_location_accesslv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch_location',
            name='Username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='district_office',
            name='Username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='head_office',
            name='Username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
