# Generated by Django 4.1.3 on 2024-07-07 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Platter_App', '0003_alter_branch_location_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch_location',
            old_name='BL_id',
            new_name='DO_id',
        ),
    ]
